# Generated by Django 3.1.7 on 2021-03-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.TextField(max_length=6000, verbose_name='Сообщение'),
        ),
    ]
